
// Auto-generate generations starting from 18 (2002/2003) up to current - 2 years
export const generateGenerations = () => {
    const generations = []
    const startGen = 18
    const startYear = 2002

    // "Angkatan -2 tahun karna belum jadi alumni"
    // Example: Current 2024 -> Show until 2022 (Batch 38) ? 
    // Or does it mean "Current Batch is 42, but Alumni is up to 40"?
    // If current year is 2025. 2025 - 2002 = 23. 18+23 = 41.
    // User said "terbaru 40". 
    // If User says "terbaru 40", and current year is roughly 2024/2025.
    // Let's use `currentYear - 2` as the safety buffer for "Alumni Status".

    const currentYear = new Date().getFullYear()
    const endYear = currentYear - 2 // Strict limit as per request

    for (let year = startYear; year <= endYear; year++) {
        const gen = startGen + (year - startYear)
        const nextYear = year + 1
        generations.push(`${gen} (${year}/${nextYear})`)
    }
    return generations.reverse() // Newest first
}

export const GENDERS = ['LAKI-LAKI', 'PEREMPUAN']

export const GENERATIONS = generateGenerations()

export const EDUCATION_LEVELS = ['D4', 'S1', 'S2', 'S3']

export const COUNTRIES = [
    'INDONESIA', 'AFGANISTAN', 'AFRIKA SELATAN', 'ALBANIA', 'ALJAZAIR', 'AMERIKA SERIKAT', 'ANDORRA', 'ANGOLA',
    'ANTIGUA DAN BARBUDA', 'ARAB SAUDI', 'ARGENTINA', 'ARMENIA', 'AUSTRALIA', 'AUSTRIA', 'AZERBAIJAN', 'BAHAMA',
    'BAHRAIN', 'BANGLADESH', 'BARBADOS', 'BELANDA', 'BELARUS', 'BELGIA', 'BELIZE', 'BENIN', 'BHUTAN', 'BOLIVIA',
    'BOSNIA DAN HERZEGOVINA', 'BOTSWANA', 'BRASIL', 'BRITANIA RAYA (INGGRIS)', 'BRUNEI DARUSSALAM', 'BULGARIA',
    'BURKINA FASO', 'BURUNDI', 'CABO VERDE', 'CEKO (REPUBLIK CEKO)', 'CHAD', 'CHILI', 'CHINA (TIONGKOK)', 'DENMARK',
    'DJIBOUTI', 'DOMINIKA', 'EKUADOR', 'EL SALVADOR', 'ERITREA', 'ESTONIA', 'ESWATINI', 'ETHIOPIA', 'FIJI',
    'FILIPINA', 'FINLANDIA', 'GABON', 'GAMBIA', 'GEORGIA', 'GHANA', 'GRENADA', 'GUATEMALA', 'GUINEA',
    'GUINEA-BISSAU', 'GUINEA KHATULISTIWA', 'GUYANA', 'HAITI', 'HONDURAS', 'HUNGARIA', 'INDIA', 'IRAK', 'IRAN',
    'IRLANDIA', 'ISLANDIA', 'ISRAEL', 'ITALIA', 'JAMAIKA', 'JEPANG', 'JERMAN', 'KAMBOJA', 'KAMERUN', 'KANADA',
    'KAZAKHSTAN', 'KENYA', 'KIRGIZSTAN', 'KIRIBATI', 'KOLOMBIA', 'KOMORO', 'KONGO', 'KONGO (REPUBLIK DEMOKRATIK)',
    'KOREA SELATAN', 'KOREA UTARA', 'KOSTA RIKA', 'KROASIA', 'KUBA', 'KUWAIT', 'LAOS', 'LATVIA', 'LEBANON',
    'LESOTHO', 'LIBERIA', 'LIBYA', 'LIECHTENSTEIN', 'LITHUANIA', 'LUKSEMBURG', 'MADAGASKAR', 'MAKEDONIA UTARA',
    'MALADEWA', 'MALAWI', 'MALAYSIA', 'MALI', 'MALTA', 'MAROKO', 'MARSHALL (KEPULAUAN)', 'MAURITANIA', 'MAURITIUS',
    'MEKSIKO', 'MESIR', 'MIKRONESIA', 'MOLDOVA', 'MONAKO', 'MONGOLIA', 'MONTENEGRO', 'MOZAMBIK', 'MYANMAR',
    'NAMIBIA', 'NAURU', 'NEPAL', 'NIGER', 'NIGERIA', 'NIKARAGUA', 'NORWEGIA', 'OMAN', 'PAKISTAN', 'PALAU',
    'PALESTINA', 'PANAMA', 'PANTAI GADING', 'PAPUA NUGINI', 'PARAGUAY', 'PERU', 'POLANDIA', 'PORTUGAL', 'PRANCIS',
    'QATAR', 'REPUBLIK DOMINIKA', 'RUMANIA', 'RUSIA', 'RWANDA', 'SAINT KITTS DAN NEVIS', 'SAINT LUCIA',
    'SAINT VINCENT DAN GRENADINES', 'SAMOA', 'SAN MARINO', 'SAO TOME DAN PRINCIPE', 'SELANDIA BARU', 'SENEGAL',
    'SERBIA', 'SEYCHELLES', 'SIERRA LEONE', 'SINGAPURA', 'SIPRUS', 'SLOVAKIA', 'SLOVENIA', 'SOLOMON (KEPULAUAN)',
    'SOMALIA', 'SPANYOL', 'SRI LANKA', 'SUDAN', 'SUDAN SELATAN', 'SURIAH', 'SURINAME', 'SWEDIA', 'SWISS',
    'TAJIKISTAN', 'TANZANIA', 'THAILAND', 'TIMOR-LESTE', 'TOGO', 'TONGA', 'TRINIDAD DAN TOBAGO', 'TUNISIA',
    'TURKI', 'TURKMENISTAN', 'TUVALU', 'UGANDA', 'UKRAINA', 'UNI EMIRAT ARAB', 'URUGUAY', 'UZBEKISTAN', 'VANUATU',
    'VATIKAN', 'VENEZUELA', 'VIETNAM', 'YAMAN', 'YORDANIA', 'YUNANI', 'ZAMBIA', 'ZIMBABWE'
]

export const PROVINCES = [
    'ACEH', 'BALI', 'BANTEN', 'BENGKULU', 'DI YOGYAKARTA', 'DKI JAKARTA', 'GORONTALO', 'JAMBI', 'JAWA BARAT',
    'JAWA TENGAH', 'JAWA TIMUR', 'KALIMANTAN BARAT', 'KALIMANTAN SELATAN', 'KALIMANTAN TENGAH', 'KALIMANTAN TIMUR',
    'KALIMANTAN UTARA', 'KEPULAUAN BANGKA BELITUNG', 'KEPULAUAN RIAU', 'LAMPUNG', 'MALUKU', 'MALUKU UTARA',
    'NUSA TENGGARA BARAT', 'NUSA TENGGARA TIMUR', 'PAPUA', 'PAPUA BARAT', 'PAPUA BARAT DAYA', 'PAPUA PEGUNUNGAN',
    'PAPUA SELATAN', 'PAPUA TENGAH', 'RIAU', 'SULAWESI BARAT', 'SULAWESI SELATAN', 'SULAWESI TENGAH',
    'SULAWESI TENGGARA', 'SULAWESI UTARA', 'SUMATERA BARAT', 'SUMATERA SELATAN', 'SUMATERA UTARA'
]

export const UNIVERSITIES = [
    'IAIN KUDUS', 'INSTITUT KESENIAN JAKARTA', 'INSTITUT PERTANIAN BOGOR', 'INSTITUT SENI INDONESIA YOGYAKARTA',
    'INSTITUT TEKNOLOGI BANDUNG', 'INSTITUT TEKNOLOGI HARAPAN BANGSA', 'INSTITUT TEKNOLOGI KALIMANTAN',
    'INSTITUT TEKNOLOGI NASIONAL', 'INSTITUT TEKNOLOGI SEPULUH NOPEMBER', 'POLITEKNIK ELEKTRONIKA NEGERI SURABAYA',
    'POLITEKNIK NEGERI BANDUNG', 'POLITEKNIK NEGERI BATAM', 'POLITEKNIK NEGERI MALANG', 'POLITEKNIK NEGERI SAMARINDA',
    'POLITEKNIK NEGERI SEMARANG', 'SEKOLAH TINGGI ILMU EKONOMI MALANGKUCECWARA', 'SEKOLAH TINGGI ILMU EKONOMI YKPN',
    'STKIP ABDI WACANA WAMENA', 'UNIVERSITAS AIRLANGGA', 'UNIVERSITAS ANDALAS', 'UNIVERSITAS ATMA JAYA YOGYAKARTA',
    'UNIVERSITAS BANGKA BELITUNG', 'UNIVERSITAS BENGKULU', 'UNIVERSITAS BINA NUSANTARA', 'UNIVERSITAS BORNEO TARAKAN',
    'UNIVERSITAS BRAWIJAYA', 'UNIVERSITAS CENDRAWASIH', 'UNIVERSITAS DIAN NUSWANTORO', 'UNIVERSITAS DIPONEGORO',
    'UNIVERSITAS HALU OLEO', 'UNIVERSITAS ISLAM BANDUNG', 'UNIVERSITAS ISLAM MALANG', 'UNIVERSITAS ISLAM NEGERI SUNAN AMPEL',
    'UNIVERSITAS ISLAM NEGERI SUNAN GUNUNG DJATI', 'UNIVERSITAS ISLAM NEGERI SUNAN KALIJAGA',
    'UNIVERSITAS ISLAM NEGERI SYARIF HIDAYATULLAH', 'UNIVERSITAS ISLAM NEGERI WALISONGO', 'UNIVERSITAS JAMBI',
    'UNIVERSITAS JEMBER', 'UNIVERSITAS JENDERAL ACHMAD YANI', 'UNIVERSITAS JENDERAL SOEDIRMAN',
    'UNIVERSITAS KATOLIK INDONESIA ATMA JAYA', 'UNIVERSITAS KATOLIK PARAHYANGAN', 'UNIVERSITAS KATOLIK SOEGIJAPRANATA',
    'UNIVERSITAS KATOLIK WIDYA MANDALA SURABAYA', 'UNIVERSITAS KHAIRUN', 'UNIVERSITAS KRISTEN DUTA WACANA',
    'UNIVERSITAS KRISTEN MARANATHA', 'UNIVERSITAS KRISTEN PAPUA', 'UNIVERSITAS KRISTEN SATYA WACANA',
    'UNIVERSITAS KRISTEN WIRA WACANA SUMBA', 'UNIVERSITAS LAMBUNG MANGKURAT', 'UNIVERSITAS LAMPUNG', 'UNIVERSITAS MA CHUNG',
    'UNIVERSITAS MATARAM', 'UNIVERSITAS MERDEKA', 'UNIVERSITAS MUHAMMADIYAH JEMBER', 'UNIVERSITAS MUHAMMADIYAH KUDUS',
    'UNIVERSITAS MUHAMMADIYAH MALANG', 'UNIVERSITAS MURIA KUDUS', 'UNIVERSITAS MUSAMUS MERAUKE', 'UNIVERSITAS MUSLIM INDONESIA',
    'UNIVERSITAS NAHDATUL ULAMA', 'UNIVERSITAS NASIONAL', 'UNIVERSITAS NASIONAL KARANGTURI SEMARANG',
    'UNIVERSITAS NEGERI GORONTALO', 'UNIVERSITAS NEGERI JAKARTA', 'UNIVERSITAS NEGERI MAKASSAR', 'UNIVERSITAS NEGERI MALANG',
    'UNIVERSITAS NEGERI PAPUA', 'UNIVERSITAS NEGERI SEBELAS MARET', 'UNIVERSITAS NEGERI SEMARANG',
    'UNIVERSITAS NEGERI YOGYAKARTA', 'UNIVERSITAS NUSA CENDANA', 'UNIVERSITAS PADJADJARAN', 'UNIVERSITAS PALANGKARAYA',
    'UNIVERSITAS PARAMADINA', 'UNIVERSITAS PASUNDAN', 'UNIVERSITAS PATTIMURA',
    'UNIVERSITAS PEMBANGUNAN NASIONAL VETERAN JAWA TIMUR', 'UNIVERSITAS PEMBANGUNAN NASIONAL VETERAN YOGYAKARTA',
    'UNIVERSITAS PENDIDIKAN INDONESIA', 'UNIVERSITAS PROF. DR. MOESTOPO (BERAGAMA)', 'UNIVERSITAS RIAU',
    'UNIVERSITAS SAM RATULANGI', 'UNIVERSITAS SANATA DHARMA', 'UNIVERSITAS SEMARANG', 'UNIVERSITAS SILIWANGI',
    'UNIVERSITAS SRIWIJAYA', 'UNIVERSITAS SULAWESI BARAT', 'UNIVERSITAS SULTAN AGENG TIRTAYASA',
    'UNIVERSITAS SUMATERA UTARA', 'UNIVERSITAS SURABAYA', 'UNIVERSITAS SWADAYA GUNUNG JATI', 'UNIVERSITAS SYIAH KUALA',
    'UNIVERSITAS TADULAKO', 'UNIVERSITAS TANJUNGPURA', 'UNIVERSITAS TARUMANAGARA', 'UNIVERSITAS TRUNOJOYO',
    'UNIVERSITAS UDAYANA', 'UNIVERSITAS WARMADEWA', 'UNIVERSITAS WIDYATAMA'
]

export const FACULTIES = [
    'HUKUM', 'ILMU SOSIAL DAN ILMU POLITIK', 'EKONOMI DAN BISNIS', 'TEKNIK', 'KEDOKTERAN',
    'ILMU KOMPUTER / INFORMATIKA', 'PSIKOLOGI', 'ILMU BUDAYA', 'PERTANIAN', 'PETERNAKAN',
    'MATEMATIKA DAN IPA', 'KEGURUAN DAN ILMU PENDIDIKAN', 'KESEHATAN MASYARAKAT', 'KOMUNIKASI',
    'DESAIN DAN SENI', 'PARIWISATA', 'LAINNYA'
]

export const JOB_TYPES = [
    'AKUNTANSI / KEUANGAN / PAJAK', 'ADMINISTRASI / SEKRETARIS', 'ARSITEK / DESAIN INTERIOR',
    'DESAIN GRAFIS / MULTIMEDIA / KREATIF', 'DOKTER / PERAWAT / TENAGA MEDIS', 'EDUKASI (DOSEN / GURU / PENELITI)',
    'ENGINEERING / TEKNIK (SIPIL, MESIN, ELEKTRO, DLL)', 'HUKUM / LEGAL / NOTARIS', 'HRD / PERSONALIA / REKRUTMEN',
    'IT / SOFTWARE / DATA', 'JURNALIS / PENULIS / CONTENT', 'KONSULTAN / ANALIS', 'LOGISTIK / SUPPLY CHAIN / OPERASIONAL',
    'MARKETING / SALES / PR', 'PELAYANAN PUBLIK / ASN / TNI / POLRI', 'PENGUSAHA / FOUNDER / PEMILIK USAHA',
    'MANAJEMEN / EKSEKUTIF (CEO/GM/MANAGER)', 'MAHASISWA / PELAJAR', 'LAINNYA'
]

export const BUSINESS_FIELDS = [
    'MAKANAN DAN MINUMAN', 'KREATIF DAN SENI', 'PENDIDIKAN DAN PELATIHAN', 'MODE DAN PAKAIAN', 'PERDAGANGAN DAN DISTRIBUSI',
    'TEKNOLOGI DAN DIGITAL', 'KONSTRUKSI DAN PROPERTI', 'PENYEDIAAN BARANG DAN PELAYANAN', 'MANUFAKTUR DAN PRODUKSI',
    'PERTANIAN DAN PETERNAKAN', 'KOMUNIKASI DAN MEDIA', 'KESEHATAN DAN KECANTIKAN', 'HIBURAN DAN REKREASI',
    'TRANSPORTASI DAN LOGISTIK', 'KEUANGAN DAN INVESTASI', 'PENELITIAN DAN PENGEMBANGAN', 'LINGKUNGAN DAN ENERGI',
    'PERJALANAN DAN PARIWISATA', 'HUKUM / JASA HUKUM', 'LAINNYA'
]

export const INDUSTRY_SECTORS = [
    'PEMERINTAHAN / BUMN', 'PENDIDIKAN / AKADEMISI', 'KESEHATAN / MEDIS', 'TEKNOLOGI / IT / STARTUP',
    'KEUANGAN / PERBANKAN / ASURANSI', 'KONSTRUKSI / PROPERTI', 'ENERGI / MIGAS / PERTAMBANGAN', 'MANUFAKTUR / PABRIK',
    'RETAIL / PERDAGANGAN / FMCG', 'MEDIA / KREATIF / HIBURAN', 'HUKUM / LEGAL', 'PARIWISATA / HOTEL / F&B',
    'LOGISTIK / TRANSPORTASI', 'PERTANIAN / PERKEBUNAN', 'LSM / NON-PROFIT', 'JASA PROFESIONAL / KONSULTAN', 'LAINNYA'
]
